### ISSUE TITLE
Website Milestone

### ISSUE THREAD

**Issue by jackcoberman** [SCCapstone/Delta#478]
- [ ] Video Demo
- [ ] Send in Headshots and LinkedIn links
- [ ] About Us Page
- [ ] Marketing on Home Page
- [ ] Some text describing how to navigate the app
- [ ] At least 3 pretty screenshots
